"""empty message

Revision ID: 143e93de530d
Revises: 1501b4e891d6
Create Date: 2025-09-20 16:52:37.259228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143e93de530d'
down_revision = '1501b4e891d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.Integer(), nullable=True),
    sa.Column('mobile_no', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_details')
    # ### end Alembic commands ###
