"""empty message

Revision ID: 1501b4e891d6
Revises: 4c2612e319cd
Create Date: 2025-09-20 14:49:00.775037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1501b4e891d6'
down_revision = '4c2612e319cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('important_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_type', sa.Enum('BIRTH', 'DEATH', 'MARRIAGE', name='importantdatetypeenum'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('important_dates')
    # ### end Alembic commands ###
