"""empty message

Revision ID: 304bdd1da601
Revises: b4a2f43440c7
Create Date: 2025-09-20 20:08:15.566020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304bdd1da601'
down_revision = 'b4a2f43440c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('relative_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Enum('PARENT', 'STEPPARENT', 'CHILD', 'STEPCHILD', 'SIBLING', 'HALFSIBLING', 'STEPSIBLING', 'SPOUSE', 'EXSPOUSE', 'UNKNOWN', name='relativestypeenum'), nullable=False),
    sa.ForeignKeyConstraint(['relative_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relatives')
    # ### end Alembic commands ###
