"""empty message

Revision ID: b4a2f43440c7
Revises: 143e93de530d
Create Date: 2025-09-20 16:56:17.546677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a2f43440c7'
down_revision = '143e93de530d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_details', schema=None) as batch_op:
        batch_op.alter_column('mobile_no',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_details', schema=None) as batch_op:
        batch_op.alter_column('mobile_no',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
